export const posterUrl =
  "https://docs.google.com/presentation/d/1y4jAfBm8XVSH0OIO-Lng9KiDSItrkRyFKN2p0tGAats/edit?usp=sharing";

export const essays = [
  {
    number: 1,
    abstractTitle:
      "Beyond Detection: Authentic Thinking as a Framework for Grading in the Age of AI",
    author: "Trent Kays",
    slug: "beyond-detection",
    abstract: [
      "The proliferation of generative AI has created an assessment crisis with institutions responding through detection software and restrictive policies. These approaches treat AI as poison to be eliminated rather than engaging deeper pedagogical questions about what we value in student work. Bernard Stiegler's philosophy of technics (particularly his concept of authentic thinking) offers a more productive framework for reimagining grading in response to AI.",
      "This theoretical exploration investigates how Stiegler's concepts of authentic versus inauthentic thinking and individuation can inform both traditional grading's failures and alternative grading's potential to foster genuine intellectual engagement in AI-saturated environments.",
      'Stiegler distinguishes authentic thinking (individual engagement requiring struggle and active participation) from inauthentic thinking (passive consumption of pre-formed thoughts). Traditional grading, which emphasizes standardized products and algorithmic evaluation, already functions as an "industrial temporal object" that synchronizes consciousness and discourages authentic engagement. AI tools simply make visible what has long been true: traditional grading often fails to require or reward authentic thinking.',
      'Alternative grading practices, such as ungrading, specifications grading, process-based assessment, align with Stieglerian authentic thinking by: (1) emphasizing iterative revision over single-draft products, (2) valuing learning processes over polished products, (3) using qualitative feedback rather than quantitative ranking, and (4) creating conditions for genuine individuation rather than synchronized performance. The question shifts from "how do we prevent AI use?" to "how do we design grading requiring authentic thinking?"',
      "This framework offers alternative grading practitioners philosophical grounding for why their approaches aren't merely pragmatic but pedagogically sound in fostering authentic intellectual development.",
    ],
    essay: [
      "Questioning the design of grading is quite timely, and I think it has the highest potential, of grading research concerns, to yield the structural changes Education needs. I'm dissatisfied, however, with Professor Kays' implicit framing of where the design problem lies: in the conception of education, in the justification of alternative grading pedagogy.",
      "These are not the critical design challenges; contrary to popular belief, refining them will not affect the institution. There's been an ancient political struggle between the spiritual and utilitarian camps of education - Professor Mehta writes about these battling paradigms in the American context in his book, The Allure of Order. Historically, the utilitarian camp always seems to be dominant. Why? Because they've wielded greater political, economic, and social influence? Because the spiritual camps' arguments aren't clear or convincing enough?",
      "That conclusion - hypothesis, rather - is a reach. There's another hypothesis we must reject before continuing to consider the former: that the utilitarian camp has dominated because they accommodate, implicitly or explicitly, critical constraints that the spiritual camp does not. These constraints are not fabrications, but rather emergent from organizing and interoperating an institution at scale. They are generally logistical: economic constraints, supply chain constraints, communication restraints.",
      "There is not nearly enough evidence to reject this hypothesis. My suspicion is that it is actually correct. In fact, I hope it is because it's deterministically solvable, especially compared to problem space implied by the original hypothesis. We can control our fate in the latter paradigm; less so in the former.",
      "A provocative read of Kays' abstract is that it furthers the status quo in reinforcing the dichotomy between the spiritual and utilitarian camps. I think this dichotomy has been fruitless politically, and I don't see a strong reason why that would change, so continuing to invest in this paradigm seems unproductive.",
      "We all sense, I think, that the status quo is untenable and change is in the air. I would like to see the institution of Education emerge more structurally sound, rather than decorated with scraps of educational concessions after decades of battle, as has historically been the case. It isn't enough this time. Those victories seem always to be hard-won and short-lived.",
      "So, instead of warring over best practice, I think we should work together to get the institution right.",
    ],
  },
  {
    number: 2,
    abstractTitle: "Rethinking the Grade: Problems with Traditional Grading",
    author: "Ashleigh Fox",
    slug: "rethinking-the-grade",
    abstract: [
      'This session situates alternative grading within decades of research critiquing traditional grading practices as ineffective and, in many cases, harmful to students. The talk will define "traditional grading" and provide a brief overview of its history before transitioning to the literature exploring the problems with traditional grading and learning, particularly regarding motivation (Blum, 2020; Butler, 1998; Chamberlin et al., 2018), consistency (Brookhart et al., 2016; Starch & Elliot, 1912), equity (Ashby-King et al., 2021; Chemaly, 2015; Inoue, 2020; Lince, 2021; Rapchak et al. 2023), mental health (Bouchrika, 2020; De Luca et al., 2016; Reinberg, 2018), and self-efficacy (Anderson, 2018; Lake et al., 2018). In light of these limitations, the session concludes by suggesting that alternative grading methods may better support learning through reflection of real-world contexts and recognition of the diverse ways individuals acquire and demonstrate knowledge.',
    ],
    essay: [
      "In my response to Professor Kays' Beyond Detection abstract, I question wars of best practice and which problems we focus on: the justification of grading pedagogy versus constraints preventing better design. Those questions echo as I read this abstract, but instead of repeating them, I want to discuss a different concern: heuristic versus core issues in education.",
      "The abstract lists several problems exacerbated by traditional grading - motivation, consistency, equity, mental-health, and self-efficacy - and it could list many more. Education entails an overwhelming number of issues, many intertwined, and each non-trivial. We could try to analyze and address each, but I suspect this is a sign that we're thinking at the wrong level of abstraction. It's a sign that those issues are heuristic, in the same way that students' economic success is a heuristic.",
      "Despite their significance, neither is core to education, and as a result, focusing them risks producing noise instead of clarity. In fact, the more significant a heuristic issue is, the higher this risk is, because the significance makes it difficult, uncomfortable, and socially risky to shelve. So when an educational discussion focuses on mental health and sociological issues, I grow wary, not because they're not important, not because they're not acute, but because they aren't goals of education. They're not why education exists.",
      "However, I don't think Professor Fox is falling for this trap. She's using them as indicators that traditional grading and the status quo aren't working well, supporting the need for grading methods more conducive to learning. No - I'm worried that advocates or designers of alternative grading methods may leave the session with disproportionate attention towards heuristic issues, rather than the role of grades and education. The latter will help simplify the design and adoption of grading, but I worry the former will complicate it.",
      "\"Traditional\" grading is, after all, a relatively new phenomenon; it isn't well understood. One general theme I expect to emerge, eventually, is that alternative grading methods try to get out of the way of education. I hope the session will explore why grades are in the way and what's stopping them from getting out. Excited for this session.",
    ],
  },
  {
    number: 3,
    abstractTitle: "How Students Experience an Ungraded Classroom",
    author: "Sarah Beal",
    slug: "ungraded-classroom",
    abstract: [
      "This panel will bring together three students from two different ungraded courses that were taught during the proposer's first implementation of an alternative grading approach. In these ungraded courses, students received formative feedback throughout the semester and engaged in guided grading reflections. They then met with the instructor individually at the end of the semester to self-assign their own final grades.",
      "The student panelists will be invited to provide an honest account of their experiences in these courses. They will share their first impressions, discomforts, and uncertainties. They will also share how this grading approach impacted their motivation in the course and their perception of academic challenge. The panel will include students from different majors, different background experiences, and different neurotypes to emphasize how experiences can vary across diverse identities.",
      "This panel is for instructors who are interested in experimenting with alternative grading practices or those already engaged in such approaches. They will gain insight into how students perceive self-evaluation, the impact that new grading approaches have on students' perceptions of workload and anxiety, and where there are opportunities to better support students, especially those who are neurodivergent. The primary objective of this session is to emphasize the role of students as active agents in shaping alternative grading approaches.",
      "Questions: 1.) What was your first impression of the ungraded format and how did your perception of self-assessment change throughout the semester? 2.) What was challenging about the grading approach? How did you adapt or what support from your instructor was most helpful? 3.) Do you think that this grading approach enhanced your learning experience? 4.) What do you wish the instructor would have done differently? 5.) What advice would you give to future instructors who use this approach? What advice would you give to future students?",
    ],
    essay: [
      "The point of this panel might not be to progress reform, but many in general do have that ambition, so that lens is what's motivating this essay. I say this cautiously, as a recent student: I question whether conversations like this move the needle. On the contrary, I worry they could influence us in unconstructive directions, such as disproportionately valuing a practice's popularity with students.",
      "De facto, student perception is a factor in evaluating grading practice, but it's a heuristic and a constraint. It shouldn't be treated as a design principle, which could be implied in emphasizing students as active agents in shaping alternative grading approaches. Confusing grading-approach with education, especially at the level of design, seems counter-productive and arguably anti-educational (for example, in a Deweyan sense).",
      "In other essays, I've gestured at the broad political and philosophical dichotomy in education as the spiritual and utilitarian camps, where the spiritual camp prizes the philosophical and sociological facets of education but the utilitarian camp favors systemization, predictability, and effectiveness, economic or otherwise. In both camps, however, student perception - actually any stakeholder's perception - is best seen as a heuristic concern.",
      "But what is student perception a heuristic for? Students' interests and needs, I think, in the abstract educational and economic senses: interest in better understanding the world and oneself; interest in social and economic progress. And the shape of their relationship to grading is obvious: it is adversarial. In fact, it's sometimes argued that grades are designed to inhibit these interests.",
      "In light of this, isn't it futile, in broad strokes, to interview student perception of alternatives, which are inspired directly by the status quo's adversarial nature? I would expect these conversations to yield insight oriented around the reduction or mitigation of this adversarial relationship, but that addresses a symptom, not the disease itself, nor movement towards the students' interests. So I fear the relief resulting from these insights might be temporary, especially as alternative practices coexist inside a dominant, adversarial paradigm.",
      "I'm not interested in incremental band aids anymore; I don't think any of us should be. Students need more, Education needs more, and grading is only a part of the puzzle. We can't lose sight of that. Iterative improvements make sense in isolation, but the issues in education aren't isolated, and the system and inertia are such that the issues are compounding and expanding at a rate overwhelming the cumulative improvements in various facets of education. Heuristically, this is why policy and pedagogical reform historically feel like they're too little too late. I don't think we can afford that anymore - is there a point when we're too late?",
      "We know the education system is in a bad place; we know there are untenable flaws in grading practices and many other practices of the system, so shouldn't we be figuring out better plans to fix them? Are students on the critical path for that?",
    ],
  },
] as const;

export type GradingConferenceEssay = (typeof essays)[number];
