baseURL: "https://pujitm.com"
languageCode: "en-us"
title: "Pujit Mehrotra"
pygmentsstyle: "monokai"

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
taxonomies:
  author: authors
